services:
    app:
        build: .
        container_name: node-api
        # Quitamos la línea 'user:' de aquí para que inicie como root
        env_file:
            - .env
        volumes:
            - ./api:/app/api
            - ./api/node_modules:/app/api/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PNPM_HOME=/root/.pnpm
            - PATH=/root/.pnpm:$PATH
        expose:
            - "3000"
    gateway:
        image: nginx:stable-alpine
        container_name: nginx-gateway
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
